site_name: Neighbors Documentation
site_url: https://theboogle.github.io/neighbors-documentation/

repo_name: Neighbors Documentation
repo_url: https://github.com/TheBoogle/neighbors-documentation

base_url: /neighbors-documentation/

theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate
    primary: black
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: 🔗
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences